packer {
  required_plugins {
    windows-update = {
      version = "0.14.3"
      source  = "github.com/rgl/windows-update"
    }
  }
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  cloud_environment_name            = "AzureUSGovernmentCloud"
  tenant_id                        = var.tenant_id
  client_id                         = var.client_id
  client_secret                     = var.client_secret
  subscription_id                   = var.subscription_id
  build_resource_group_name         = var.build_resource_group_name
  communicator                      = "winrm"
  image_offer                       = var.image_offer
  image_publisher                   = var.image_publisher
  image_sku                         = var.image_sku
  managed_image_name                = var.managed_image_name
  managed_image_resource_group_name = var.managed_image_resource_group_name
  os_type                           = var.os_type
  vm_size                           = var.vm_size
  shared_image_gallery_destination {
    subscription         = "0e4cfcad-ab43-48e2-9e53-2b0a2624a8c7"
    resource_group       = "cfo-rg-sharedServices-compute-gallery"
    gallery_name         = "cloudfitonline_image_gallery"
    image_name           = "avd-win11"
    image_version        = "0.1.4"
    replication_regions  = ["usgovvirginia"]
    storage_account_type = "Standard_LRS"
  }
  winrm_insecure = true
  winrm_timeout  = "5m"
  winrm_use_ssl  = true
  winrm_username = "packer"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "powershell" {
    inline = [
      "  while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "  while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }"
    ]
  }
  provisioner "windows-update" {
    search_criteria = "IsInstalled=0"
    filters = [
      "exclude:$_.Title -like '*Preview*'",
      "include:$true",
    ]
    update_limit = 1000
  }

  provisioner "powershell" {
    elevated_user     = build.User
    elevated_password = build.Password
    script            = "setup/openssh.ps1"
  }

  provisioner "ansible" {
    playbook_file          = "playbooks/win11-withFslogix-agent.yml"
    user                   = build.User
    use_proxy              = false
    ansible_ssh_extra_args = ["-o IdentitiesOnly=yes", "-o StrictHostKeyChecking=no", "-o UserKnownHostsFile=/dev/null"]
    extra_arguments = [
      "--extra-vars",
      "ansible_user=${build.User} ansible_password=${build.Password} ansible_become_user=${build.User} ansible_port=22 ansible_shell_type=powershell ansible_become_method=runas ansible_connection=ssh ansible_ssh_retries=30"
    ]
  }

  provisioner "powershell" {
    inline = [
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm",
      "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
    ]
  }
}