source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  build_resource_group_name         = var.build_resource_group_name
  client_id                         = "600030f0-99e2-455f-9398-f91a7ce9e049"
  client_secret                     = "RKJ8Q~4oX1eL8_H5PQ1LN2g1.kSzlbF4TrZRldA~"
  communicator                      = "winrm"
  image_offer                       = var.image_offer
  image_publisher                   = var.image_publisher
  image_sku                         = var.image_sku
  managed_image_name                = var.managed_image_name
  managed_image_resource_group_name = var.managed_image_resource_group_name
  os_type                           = var.os_type
  subscription_id                   = "9a09c126-ca50-4406-a438-899badcf2828"
  tenant_id                         = "b846a774-f39d-4a2d-9366-f3dda22c6bf0"
  vm_size                           = "Standard_B2ms"
  shared_image_gallery_destination {
    subscription            = "9a09c126-ca50-4406-a438-899badcf2828"
    resource_group          = "rg-avd-packer-builds"
    gallery_name            = "cf_image_depot"
    image_name              = "windows-11-avd-multisession-stig"
    image_version           = "0.1.3"
    replication_regions     = ["eastus"]
    storage_account_type    = "Standard_LRS"
  }
  winrm_insecure                    = true
  winrm_timeout                     = "5m"
  winrm_use_ssl                     = true
  winrm_username                    = "packer"


}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "powershell" {
   inline = [
        "  while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
        "  while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }"
   ]
  }

  provisioner "powershell" {
    elevated_user     = build.User
    elevated_password = build.Password
    script            = "setup/openssh.ps1"
  }

  provisioner "ansible" {
    playbook_file = "playbooks/win11-withFslogix-agent.yml"
    user          = build.User
    use_proxy     = false
    ansible_ssh_extra_args  = ["-o IdentitiesOnly=yes", "-o StrictHostKeyChecking=no", "-o UserKnownHostsFile=/dev/null"]
    extra_arguments = [
      "--extra-vars",
      "ansible_user=${build.User} ansible_password=${build.Password} ansible_become_user=${build.User} ansible_port=22 ansible_shell_type=powershell ansible_become_method=runas ansible_connection=ssh ansible_ssh_retries=30"
    ]
  }

  provisioner "powershell" {
   inline = [
        "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm",
        "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
   ]
  }
}