source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  build_resource_group_name         = "rg-avd-packer-builds"
  client_id                         = "600030f0-99e2-455f-9398-f91a7ce9e049"
  client_secret                     = "RKJ8Q~4oX1eL8_H5PQ1LN2g1.kSzlbF4TrZRldA~"
  communicator                      = "winrm"
  image_offer                       = "windows-11"
  image_publisher                   = "microsoftwindowsdesktop"
  image_sku                         = "win11-21h2-avd"
  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "rg-avd-packer-builds"
  os_type                           = "Windows"
  subscription_id                   = "9a09c126-ca50-4406-a438-899badcf2828"
  tenant_id                         = "b846a774-f39d-4a2d-9366-f3dda22c6bf0"
  vm_size                           = "Standard_B2s"
  winrm_insecure                    = true
  winrm_timeout                     = "5m"
  winrm_use_ssl                     = true
  winrm_username                    = "packer"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "powershell" {
   inline = [
        "  while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
        "  while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }"
   ]
  }

  provisioner "powershell" {
    elevated_user     = build.User
    elevated_password = build.Password
    script            = "./openssh.ps1"
  }

  provisioner "ansible" {
    playbook_file = "./windows_11_MS_securityBaseline.yml"
    user          = build.User
    use_proxy     = false
    ansible_ssh_extra_args  = ["-o IdentitiesOnly=yes", "-o StrictHostKeyChecking=no", "-o UserKnownHostsFile=/dev/null"]
    extra_arguments = [
      "--extra-vars",
      "ansible_user=${build.User} ansible_password=${build.Password} ansible_become_user=${build.User} ansible_port=22 ansible_shell_type=powershell ansible_become_method=runas ansible_connection=ssh ansible_ssh_retries=30"
    ]
  }

  provisioner "powershell" {
   inline = [
        "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm",
        "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
   ]
  }
}