source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  build_resource_group_name         = "rg-avd-packer-builds"
  client_id                         = "600030f0-99e2-455f-9398-f91a7ce9e049"
  client_secret                     = "RKJ8Q~4oX1eL8_H5PQ1LN2g1.kSzlbF4TrZRldA~"
  communicator                      = "winrm"
  image_offer                       = "windows-11"
  image_publisher                   = "microsoftwindowsdesktop"
  image_sku                         = "win11-21h2-avd"
  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "rg-avd-packer-builds"
  os_type                           = "Windows"
  subscription_id                   = "9a09c126-ca50-4406-a438-899badcf2828"
  tenant_id                         = "b846a774-f39d-4a2d-9366-f3dda22c6bf0"
  vm_size                           = "Standard_B1s"
  winrm_insecure                    = true
  winrm_timeout                     = "5m"
  winrm_use_ssl                     = true
  winrm_username                    = "packer"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "ansible" {
    playbook_file = "./windows_11_MS_securityBaseline.yml"
    user          = build.User
    use_proxy     = false
    extra_arguments = [
      "-e",
      "ansible_winrm_server_cert_validation=ignore",
      "--connection", "packer",
      "--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"
    ]
  }
}