parameters:
  - name: avdSubServiceConnection
    type: string
    default: "cloudfitonline_avd_deployer"
  - name: imageGalleryResourceGroupName
    type: string
    default: 'cfoavd-rg-cfsgaia-prod'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt install packer
    pip3 install ansible
    echo "Packer path:" `which packer`
    echo "Ansible path:" `which ansible`
    echo "Ansible playbook path:" `which ansible-playbook`
  displayName: "Install cmd line tools/requirements"
- task: AzureCLI@2
  displayName: "Initialize terraform for gallery container creation"
  inputs:
    azureSubscription: ${{ parameters.avdSubServiceConnection }}
    scriptType: 'bash'
    addSpnToEnvironment: true
    useGlobalConfig: true
    scriptLocation: 'inlineScript'
    inlineScript: |
      ls $(Build.SourcesDirectory) ;\
      packer build -force -var-file=$(Build.SourcesDirectory)/win11-withFsLogixAndSTIG.pkrvars.hcl . \
      # az sig image-definition create --resource-group ${{ parameters.imageGalleryResourceGroupName }} \
      # --gallery-name cloudfitonline_image_gallery --gallery-image-definition win11-stig-and-fslogix \
      # --publisher microsoftwindowsdesktop --offer office-365 --sku win11-21h2-avd-m365 \
      # --os-type windows --os-state Generalized
# az sig image-definition create --resource-group MyResourceGroup \
# --gallery-name MyGallery --gallery-image-definition MyImage \
# --publisher GreatPublisher --offer GreatOffer --sku GreatSku \
# --os-type windows --os-state Generalized
