parameters:
  - name: avdSubServiceConnection
    type: string
    default: "cloudfitonline_avd_deployer"

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt install packer
    pip3 install ansible
    echo "Packer path:" `which packer` || echo "Packer not installed"
    echo "Ansible path:" `which ansible` || echo "Ansible not installed"
    echo "Ansible playbook path:" `which ansible-playbook` || echo "Ansible playbook not installed"
    which terraform
    ls -la $(Build.SourcesDirectory)
  displayName: "Install cmd line tools/requirements"
- task: AzureCLI@2
  displayName: "Initialize and build windows-11 STIG image with fsLogix agent installed"
  inputs:
                  azureSubscription: ${{ parameters.avdSubServiceConnection }}
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    ls -la $(Build.SourcesDirectory)\