parameters:
  - name: avdSubServiceConnection
    type: string
    default: "cloudfitonline_avd_deployer"

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt install packer
    pip3 install ansible
    sudo chmod 700 `which terraform`
    echo "Packer path:" `which packer`
    echo "Ansible path:" `which ansible`
    echo "Ansible playbook path:" `which ansible-playbook`
    echo "Terraform path:" `which terraform`
  displayName: "Install cmd line tools/requirements"
- task: AzureCLI@2
  displayName: "Initialize terraform for gallery container creation"
  inputs:
    azureSubscription: ${{ parameters.avdSubServiceConnection }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform -help  ;\
      ls $(Build.SourcesDirectory)/tf/ ;\

